services:
  postgres:
    image: postgres:latest
    container_name: noaa-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: noaa_station
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - noaa_postgres_data:/var/lib/postgresql/data

volumes:
  noaa_postgres_data: